In [3]:
# Import libraries
import numpy as np
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [4]:
df=pd.read_csv('./Multiple-Linear-Dataset.csv')
df.head()

Product_1  Product_2  Product_3 Location     Profit
0  165349.20  136897.80  471784.10   City_1  192261.83
1  162597.70  151377.59  443898.53   City_2  191792.06
2  153441.51  101145.55  407934.54   City_3  191050.39
3  144372.41  118671.85  383199.62   City_1  182901.99
4  142107.34   91391.77  366168.42   City_3  166187.94

In [5]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [6]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
labelencoder_X = LabelEncoder()
X[:, 3] = labelencoder_X.fit_transform(X[:, 3])
onehotencoder = ColumnTransformer([("Location", OneHotEncoder(), [3])], remainder="passthrough")
X=onehotencoder.fit_transform(X)

# Eliminating the Dummy Variable
X = X[:, 1:]
X

array([[0.0, 0.0, 165349.2, 136897.8, 471784.1],
       [1.0, 0.0, 162597.7, 151377.59, 443898.53],
       [0.0, 1.0, 153441.51, 101145.55, 407934.54],
       [0.0, 0.0, 144372.41, 118671.85, 383199.62],
       [0.0, 1.0, 142107.34, 91391.77, 366168.42],
       [0.0, 0.0, 131876.9, 99814.71, 362861.36],
       [1.0, 0.0, 134615.46, 147198.87, 127716.82],
       [0.0, 1.0, 130298.13, 145530.06, 323876.68],
       [0.0, 0.0, 120542.52, 148718.95, 311613.29],
       [1.0, 0.0, 123334.88, 108679.17, 304981.62],
       [0.0, 1.0, 101913.08, 110594.11, 229160.95],
       [1.0, 0.0, 100671.96, 91790.61, 249744.55],
       [0.0, 1.0, 93863.75, 127320.38, 249839.44],
       [1.0, 0.0, 91992.39, 135495.07, 252664.93],
       [0.0, 1.0, 119943.24, 156547.42, 256512.92],
       [0.0, 0.0, 114523.61, 122616.84, 261776.23],
       [1.0, 0.0, 78013.11, 121597.55, 264346.06],
       [0.0, 0.0, 94657.16, 145077.58, 282574.31],
       [0.0, 1.0, 91749.16, 114175.79, 294919.57],
       [0.0, 0.0, 86419.7

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [8]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train,y_train)

LinearRegression()

In [9]:
# Predicting the Test set results
y_pred = regressor.predict(X_test)
y_pred

array([104282.76472172, 132536.88499212, 133910.85007767,  72584.77489417,
       179920.9276189 , 114549.31079233,  66444.43261346,  98404.96840122,
       114499.82808602, 169367.50639895,  96522.6253998 ,  88040.6718287 ,
       110949.99405525,  90419.1897851 , 128020.46250064])

In [11]:
# Building the optimal model using Backward Elimination
import statsmodels.api as sm
X = np.append(arr=np.ones((len(X), 1)).astype(int), values=X, axis=1)
'''
X_opt = X[:, [0, 1, 2, 3, 4]]
X_opt = np.array(X_opt, dtype=float)
regressor_OLS = sm.OLS(endog=y,exog=X_opt).fit()
regressor_OLS.summary()
X_opt = X[:, [0, 1, 3, 4]]
X_opt = np.array(X_opt, dtype=float)
regressor_OLS = sm.OLS(endog=y, exog=X_opt).fit()
regressor_OLS.summary()
X_opt = X[:, [0, 1, 4]]
X_opt = np.array(X_opt, dtype=float)
regressor_OLS = sm.OLS(endog=y, exog=X_opt).fit()
regressor_OLS.summary()
'''

X_opt = X[:, [0, 4]]
X_opt = np.array(X_opt, dtype=float)
regressor_OLS = sm.OLS(endog=y, exog=X_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.947
Model:                            OLS   Adj. R-squared:                  0.945
Method:                 Least Squares   F-statistic:                     849.8
Date:                Mon, 12 Feb 2024   Prob (F-statistic):           3.50e-32
Time:                        20:31:01   Log-Likelihood:                -527.44
No. Observations:                  50   AIC:                             1059.
Df Residuals:                      48   BIC:                             1063.
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       4.903e+04   2537.897     19.320      0.000    4.39e+04    5.41e+04
x1             0.8543      0.029     29.151      0.000       0.795       0.913
==============================================================================
Omnibus:                       13.727   Durbin-Watson:                   1.116
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               18.536
Skew:                          -0.911   Prob(JB):                     9.44e-05
Kurtosis:                       5.361   Cond. No.                     1.65e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.65e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

#### Two input features (Product_1 and Product_3); 1 output represents the estimated profit based on these two features.

In [9]:
X = df.iloc[:, [0, 2]].values
y = df.iloc[:, 4].values

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [11]:
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [12]:
# Predicting the Test set results
y_pred = regressor.predict(X_test)
y_pred

array([102284.64605183, 133873.92383812, 134182.1495165 ,  73701.1069363 ,
       180642.25299736, 114717.24903894,  68335.07575312,  97433.45922275,
       114580.92136452, 170343.31979498])